/* Generated by StringGen.exe */
public static class Strings
{
	 public static class Content
	 {
		public const string backgroundJPG = "background";
		public const string DefaultFontSPRITEFONT = "DefaultFont";
		public const string DefaultTexture32PNG = "DefaultTexture32";
		public const string NineSlicePNG = "NineSlice";
		public const string RippleFX = "Ripple";
		public const string spriteJPG = "sprite";
		public const string WorldConfigXML = "WorldConfig";
		public const string WorldConfigXSD = "WorldConfig";
		public static class Effects
		{
		}
		public static class Fonts
		{
			public const string UIFontBigSPRITEFONT = "Fonts/UIFontBig";
		}
		public static class Textures
		{
			public const string BaseHumanPNG = "Textures/BaseHuman";
			public const string BaseHumanXML = "Textures/BaseHuman";
			public const string Environment1PNG = "Textures/Environment1";
			public const string Environment1XML = "Textures/Environment1";
			public const string GearIcons1PNG = "Textures/GearIcons1";
			public const string InsideTiles1PNG = "Textures/InsideTiles1";
			public const string Tiles1PNG = "Textures/Tiles1";
			public const string Tiles1XML = "Textures/Tiles1";
			public const string WhiteTexture1PNG = "Textures/WhiteTexture1";
			public const string WhiteTexture32PNG = "Textures/WhiteTexture32";
					public static class Gui
					{
						public const string LoadingCirclePNG = "Textures/Gui/LoadingCircle";
					}
		}
	 }
}
